#############################
#####  OreRegeneration  #####
#############################

### Generate these ore types
Active Ore Types:
  DIAMOND_ORE:
    From Y: 2
    To Y: 16
    Vein Size: 2~6
  GOLD_ORE:
    From Y: 2
    To Y: 32
    Vein Size: 3~6
  EMERALD_ORE:
    From Y: 2
    To Y: 32
    Vein Size: 1~2
  LAPIS_ORE:
    From Y: 2
    To Y: 30
    Vein Size: 1~3

### Anti-Duplicate
Ignore:
  Above Y level: 63
  Placed blocks: true

### Session statistics
Record Stats: true
Debug Mode: true

### Don't touch this
Config Version: 2